server:
  port: 8001
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true  #注册服务时使用服务的IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    cn:
      fcsca:
        providerticket:
          controller: debug
debug: true