spring:
  application:
    name: consumer-user
server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true  #注册服务时使用服务的IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/